=== klisiecki/SqlDataGenerator/src/main/resources/datatypeSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified" attributeFormDefault="unqualified"
            targetNamespace="pl.poznan.put.sqldatagenerator"
            xmlns="pl.poznan.put.sqldatagenerator">

    <xs:element name="DATATYPES">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="DATATYPE" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="DATATYPE">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="NAME" type="xs:string"/>
                <xs:choice>
                    <xs:sequence>
                        <xs:element name="BASETYPE" type="xs:string"/>
                        <xs:element name="MIN_VALUE" type="xs:long"/>
                        <xs:element name="MAX_VALUE" type="xs:long"/>
                    </xs:sequence>
                    <xs:element name="ALIAS_FOR" type="xs:string"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--<xs:element name="ATTRIBUTES">-->
    <!--<xs:complexType>-->
    <!--<xs:sequence>-->
    <!--<xs:element ref="ATTRIBUTE" minOccurs="0" maxOccurs="unbounded" />-->
    <!--</xs:sequence>-->
    <!--</xs:complexType>-->
    <!--</xs:element>-->
    <!---->
    <!---->
    <!--<xs:element name="ATTRIBUTE">-->
    <!--<xs:complexType>-->
    <!--<xs:all>-->
    <!--<xs:element name="NAME" type="xs:string"/>-->
    <!--<xs:element name="NULL_PERCENTAGE" type="percentage_type" minOccurs="0" />-->
    <!--<xs:element name="TYPE" type="data_type" />-->
    <!--<xs:element name="MIN_VALUE" type="xs:integer" minOccurs="0" />-->
    <!--<xs:element name="MAX_VALUE" type="xs:integer" minOccurs="0" />-->
    <!--<xs:element ref="unique_group" minOccurs="0" maxOccurs="1"/>-->
    <!--<xs:element ref="VALUES" minOccurs="0" />-->
    <!--</xs:all>-->
    <!--</xs:complexType>-->
    <!--</xs:element>-->

    <!--<xs:element name="unique_group" abstract="true"/>-->

    <!--<xs:element name="UNIQUE_PERCENTAGE" substitutionGroup="unique_group">-->
    <!--<xs:complexType>-->
    <!--<xs:all>-->
    <!--<xs:element name="MIN" type="percentage_type" minOccurs="0" />-->
    <!--<xs:element name="MAX" type="percentage_type" minOccurs="0" />-->
    <!--</xs:all>-->
    <!--</xs:complexType>-->
    <!--</xs:element>-->

    <!--<xs:element name="PRIMARY_KEY" substitutionGroup="unique_group"  type="xs:boolean">-->
    <!--</xs:element>-->
    <!---->
    <!---->
    <!--<xs:simpleType name="data_type">-->
    <!--<xs:restriction base="xs:string">-->
    <!--<xs:enumeration value="INTEGER"/>-->
    <!--<xs:enumeration value="FLOAT"/>-->
    <!--<xs:enumeration value="VARCHAR"/>-->
    <!--<xs:enumeration value="DATETIME"/>-->
    <!--</xs:restriction>-->
    <!--</xs:simpleType>-->
    <!---->
    <!--<xs:simpleType name="percentage_type">-->
    <!--<xs:restriction base="xs:float">-->
    <!--<xs:minInclusive value="0" />-->
    <!--<xs:maxInclusive value="100" />-->
    <!--</xs:restriction>-->
    <!--</xs:simpleType>-->

    <!--<xs:element name="VALUES">-->
    <!--<xs:complexType>-->
    <!--<xs:sequence>-->
    <!--<xs:element name="VALUE" type="xs:string" maxOccurs="unbounded" />-->
    <!--</xs:sequence>-->
    <!--</xs:complexType>-->
    <!--</xs:element>-->

</xsd:schema>

=== klisiecki/SqlDataGenerator/src/main/resources/datatypes/netezza.xml
<?xml version="1.0"?>
<DATATYPES xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="pl.poznan.put.sqldatagenerator ../datatypeSchema.xsd"
           xmlns="pl.poznan.put.sqldatagenerator">

    <DATATYPE>
        <NAME>VARCHAR</NAME>
        <BASETYPE>VARCHAR</BASETYPE>
        <MIN_VALUE>1</MIN_VALUE>
        <MAX_VALUE>64000</MAX_VALUE>
    </DATATYPE>

    <DATATYPE>
        <NAME>CHAR</NAME>
        <ALIAS_FOR>VARCHAR</ALIAS_FOR>
    </DATATYPE>

    <DATATYPE>
        <NAME>CHARACTER</NAME>
        <ALIAS_FOR>VARCHAR</ALIAS_FOR>
    </DATATYPE>

    <DATATYPE>
        <NAME>CHARACTER VARYING</NAME>
        <ALIAS_FOR>VARCHAR</ALIAS_FOR>
    </DATATYPE>

    <DATATYPE>
        <NAME>CHAR VARYING</NAME>
        <ALIAS_FOR>VARCHAR</ALIAS_FOR>
    </DATATYPE>


    <DATATYPE>
        <NAME>DATETIME</NAME>
        <BASETYPE>DATETIME</BASETYPE>
        <MIN_VALUE>1900-01-01 00:00:00</MIN_VALUE>
        <MAX_VALUE>2100-12-31 23:59:59</MAX_VALUE>
    </DATATYPE>

    <DATATYPE>
        <NAME>TIMESTAMP</NAME>
        <ALIAS_FOR>DATETIME</ALIAS_FOR>
    </DATATYPE>


    <DATATYPE>
        <NAME>FLOAT</NAME>
        <BASETYPE>FLOAT</BASETYPE>
        <MIN_VALUE>-2147483648</MIN_VALUE>
        <MAX_VALUE>2147483647</MAX_VALUE>
    </DATATYPE>

    <DATATYPE>
        <NAME>REAL</NAME>
        <ALIAS_FOR>FLOAT</ALIAS_FOR>
    </DATATYPE>

    <DATATYPE>
        <NAME>DOUBLE PRECISION</NAME>
        <ALIAS_FOR>FLOAT</ALIAS_FOR>
    </DATATYPE>

    <DATATYPE>
        <NAME>DOUBLE</NAME>
        <ALIAS_FOR>FLOAT</ALIAS_FOR>
    </DATATYPE>


    <DATATYPE>
        <NAME>INTEGER</NAME>
        <BASETYPE>INTEGER</BASETYPE>
        <MIN_VALUE>-2147483648</MIN_VALUE>
        <MAX_VALUE>2147483647</MAX_VALUE>
    </DATATYPE>

    <DATATYPE>
        <NAME>INT</NAME>
        <ALIAS_FOR>INTEGER</ALIAS_FOR>
    </DATATYPE>

    <DATATYPE>
        <NAME>INT4</NAME>
        <ALIAS_FOR>INTEGER</ALIAS_FOR>
    </DATATYPE>


    <DATATYPE>
        <NAME>BYTEINT</NAME>
        <BASETYPE>INTEGER</BASETYPE>
        <MIN_VALUE>-128</MIN_VALUE>
        <MAX_VALUE>127</MAX_VALUE>
    </DATATYPE>

    <DATATYPE>
        <NAME>INT1</NAME>
        <ALIAS_FOR>BYTEINT</ALIAS_FOR>
    </DATATYPE>


    <DATATYPE>
        <NAME>SMALLINT</NAME>
        <BASETYPE>INTEGER</BASETYPE>
        <MIN_VALUE>â€“32768</MIN_VALUE>
        <MAX_VALUE>32767</MAX_VALUE>
    </DATATYPE>

    <DATATYPE>
        <NAME>INT2</NAME>
        <ALIAS_FOR>SMALLINT</ALIAS_FOR>
    </DATATYPE>


    <DATATYPE>
        <NAME>BIGINT</NAME>
        <BASETYPE>INTEGER</BASETYPE>
        <MIN_VALUE>-9223372036854775808</MIN_VALUE>
        <MAX_VALUE>9223372036854775807</MAX_VALUE>
    </DATATYPE>

    <DATATYPE>
        <NAME>INT8</NAME>
        <ALIAS_FOR>BIGINT</ALIAS_FOR>
    </DATATYPE>
</DATATYPES>
