=== klisiecki/SqlDataGenerator/src/main/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified" attributeFormDefault="unqualified"
    targetNamespace="pl.poznan.put.sqldatagenerator"
    xmlns="pl.poznan.put.sqldatagenerator" >
        
    <xs:element name="TABLES">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="TABLE" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="TABLE">
        <xs:complexType>
            <xs:all>
                <xs:element name="NAME" type="xs:string" />
                <xs:element name="ROWS_NUM" type="xs:integer" />
                <xs:element name="DISTRIBUTION" type="xs:string" minOccurs="0" />
                <xs:element name="MIN_ROW_SIZE" type="xs:integer" minOccurs="0" />
                <xs:element ref="ATTRIBUTES" minOccurs="1"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="ATTRIBUTES">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ATTRIBUTE" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    <xs:element name="ATTRIBUTE">
        <xs:complexType>
            <xs:all>
                <xs:element name="NAME" type="xs:string"/>
                <xs:element name="NULL_PERCENTAGE" type="percentage_type" minOccurs="0" />
                <xs:element name="TYPE" type="xsd:string"/>
                <xs:element name="MIN_VALUE" type="xs:integer" minOccurs="0" />
                <xs:element name="MAX_VALUE" type="xs:integer" minOccurs="0" />
                <xs:element ref="unique_group" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="VALUES" minOccurs="0" />
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="unique_group" abstract="true"/>

    <xs:element name="UNIQUE_PERCENTAGE" substitutionGroup="unique_group">
        <xs:complexType>
            <xs:all>
                <xs:element name="MIN" type="percentage_type" minOccurs="0" />
                <xs:element name="MAX" type="percentage_type" minOccurs="0" />
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="PRIMARY_KEY" substitutionGroup="unique_group"  type="xs:boolean">
    </xs:element>

    <xs:simpleType name="percentage_type">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="100" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="VALUES">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="VALUE" type="xs:string" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
   
</xsd:schema>

=== klisiecki/SqlDataGenerator/data/store.xml
<?xml version="1.0"?>
<TABLES xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="pl.poznan.put.sqldatagenerator schema.xsd"
        xmlns="pl.poznan.put.sqldatagenerator" M="200" T="100">
    <TABLE>
        <NAME>PRODUCTS</NAME>
        <ROWS_NUM>50</ROWS_NUM>
        <ATTRIBUTES>
            <ATTRIBUTE>
                <NAME>ID</NAME>
                <TYPE>INTEGER</TYPE>
                <PRIMARY_KEY>true</PRIMARY_KEY>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>NAME</NAME>
                <TYPE>STRING</TYPE>
                <MIN_VALUE>3</MIN_VALUE>
                <MAX_VALUE>10</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>DESCRIPTION</NAME>
                <TYPE>STRING</TYPE>
                <MIN_VALUE>20</MIN_VALUE>
                <MAX_VALUE>50</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>PRICE</NAME>
                <TYPE>FLOAT</TYPE>
                <MIN_VALUE>1</MIN_VALUE>
                <MAX_VALUE>10000</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>CATEGORY</NAME>
                <TYPE>STRING</TYPE>
                <VALUES>
                    <VALUE>AGD</VALUE>
                    <VALUE>RTV</VALUE>
                    <VALUE>COMPUTERS</VALUE>
                    <VALUE>ELECTRONICS</VALUE>
                </VALUES>
            </ATTRIBUTE>
            
        </ATTRIBUTES>
    </TABLE>

    <TABLE>
        <NAME>CLIENTS</NAME>
        <ROWS_NUM>100</ROWS_NUM>
        <ATTRIBUTES>
            <ATTRIBUTE>
                <NAME>ID</NAME>
                <TYPE>INTEGER</TYPE>
                <PRIMARY_KEY>true</PRIMARY_KEY>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>FIRST_NAME</NAME>
                <TYPE>STRING</TYPE>
                <MIN_VALUE>2</MIN_VALUE>
                <MAX_VALUE>15</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>LAST_NAME</NAME>
                <TYPE>STRING</TYPE>
                <MIN_VALUE>2</MIN_VALUE>
                <MAX_VALUE>15</MAX_VALUE>
            </ATTRIBUTE>

        </ATTRIBUTES>
    </TABLE>

    <TABLE>
        <NAME>ORDERS</NAME>
        <ROWS_NUM>1000</ROWS_NUM>
        <ATTRIBUTES>
            <ATTRIBUTE>
                <NAME>ID</NAME>
                <TYPE>INTEGER</TYPE>
                <PRIMARY_KEY>true</PRIMARY_KEY>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>PRODUCT_ID</NAME>
                <TYPE>INTEGER</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>CLIENT_ID</NAME>
                <TYPE>INTEGER</TYPE>
            </ATTRIBUTE>
        </ATTRIBUTES>
    </TABLE>
</TABLES>

=== klisiecki/SqlDataGenerator/data/ibm.xml
<?xml version="1.0"?>
<TABLES xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="pl.poznan.put.sqldatagenerator schema.xsd"
        xmlns="pl.poznan.put.sqldatagenerator" M="200" T="100">
    <TABLE>
        <NAME>RV_ENFCOMPLAINTS_DCA</NAME>
        <ROWS_NUM>50</ROWS_NUM>
        <ATTRIBUTES>
            <ATTRIBUTE>
                <NAME>ENF_CSE_TYP_ID</NAME>
                <TYPE>INTEGER</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>ENF_REGN_ID</NAME>
                <TYPE>INTEGER</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>BOARDCODE</NAME>
                <TYPE>VARCHAR</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>LICCODE</NAME>
                <TYPE>VARCHAR</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>ACTIVITYDATE</NAME>
                <TYPE>DATETIME</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>PENDINGENDDATE</NAME>
                <TYPE>DATETIME</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>ACTV_STRT_DTE</NAME>
                <TYPE>DATETIME</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>ACTV_END_DTE</NAME>
                <TYPE>DATETIME</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>CATEGORYORDER</NAME>
                <TYPE>INTEGER</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>ROD_REOPENDATE</NAME>
                <TYPE>DATETIME</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>ROD_CLOSEDATE</NAME>
                <TYPE>DATETIME</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>CLOSUREROWNUMBER</NAME>
                <TYPE>INTEGER</TYPE>
            </ATTRIBUTE>


        </ATTRIBUTES>
    </TABLE>


</TABLES>

=== klisiecki/SqlDataGenerator/data/ibm_1/ibm.xml
<?xml version="1.0"?>
<TABLES xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="pl.poznan.put.sqldatagenerator schema.xsd"
        xmlns="pl.poznan.put.sqldatagenerator">
    <TABLE>
        <NAME>RV_ENFCOMPLAINTS_DCA</NAME>
        <ROWS_NUM>1000</ROWS_NUM>
        <ATTRIBUTES>
            <ATTRIBUTE>
                <NAME>ID</NAME>
                <TYPE>INTEGER</TYPE>
                <PRIMARY_KEY>true</PRIMARY_KEY>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>ENF_CSE_TYP_ID</NAME>
                <TYPE>INTEGER</TYPE>
                <MIN_VALUE>0</MIN_VALUE>
                <MAX_VALUE>100</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>ENF_REGN_ID</NAME>
                <TYPE>INTEGER</TYPE>
                <MIN_VALUE>0</MIN_VALUE>
                <MAX_VALUE>10000</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>BOARDCODE</NAME>
                <TYPE>VARCHAR</TYPE>
                <MIN_VALUE>0</MIN_VALUE>
                <MAX_VALUE>5</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>LICCODE</NAME>
                <TYPE>VARCHAR</TYPE>
                <MIN_VALUE>0</MIN_VALUE>
                <MAX_VALUE>5</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>ACTIVITYDATE</NAME>
                <TYPE>DATETIME</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>PENDINGENDDATE</NAME>
                <TYPE>DATETIME</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>ACTV_STRT_DTE</NAME>
                <TYPE>DATETIME</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>ACTV_END_DTE</NAME>
                <TYPE>DATETIME</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>CATEGORYORDER</NAME>
                <TYPE>INTEGER</TYPE>
                <MIN_VALUE>0</MIN_VALUE>
                <MAX_VALUE>150</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>ROD_REOPENDATE</NAME>
                <TYPE>DATETIME</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>ROD_CLOSEDATE</NAME>
                <TYPE>DATETIME</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>CLOSUREROWNUMBER</NAME>
                <TYPE>INTEGER</TYPE>
                <MIN_VALUE>-1000000</MIN_VALUE>
                <MAX_VALUE>1000000</MAX_VALUE>
            </ATTRIBUTE>


        </ATTRIBUTES>
    </TABLE>


</TABLES>

=== klisiecki/SqlDataGenerator/src/test/resources/store_test/store.xml
<?xml version="1.0"?>
<TABLES xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="pl.poznan.put.sqldatagenerator schema.xsd"
        xmlns="pl.poznan.put.sqldatagenerator">
    <TABLE>
        <NAME>PRODUCTS</NAME>
        <ROWS_NUM>300</ROWS_NUM>
        <ATTRIBUTES>
            <ATTRIBUTE>
                <NAME>ID</NAME>
                <TYPE>INTEGER</TYPE>
                <PRIMARY_KEY>true</PRIMARY_KEY>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>NAME</NAME>
                <TYPE>VARCHAR</TYPE>
                <MIN_VALUE>3</MIN_VALUE>
                <MAX_VALUE>10</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>DESCRIPTION</NAME>
                <TYPE>VARCHAR</TYPE>
                <MIN_VALUE>1</MIN_VALUE>
                <MAX_VALUE>50</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>PRICE</NAME>
                <TYPE>FLOAT</TYPE>
                <MIN_VALUE>0</MIN_VALUE>
                <MAX_VALUE>100000</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>OLD_PRICE</NAME>
                <TYPE>FLOAT</TYPE>
                <MIN_VALUE>0</MIN_VALUE>
                <MAX_VALUE>100000</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>CATEGORY</NAME>
                <TYPE>VARCHAR</TYPE>
                <VALUES>
                    <VALUE>AGD</VALUE>
                    <VALUE>RTV</VALUE>
                    <VALUE>COMPUTERS</VALUE>
                    <VALUE>ELECTRONICS</VALUE>
                </VALUES>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>PACKAGE_WIDTH</NAME>
                <TYPE>INTEGER</TYPE>
                <MIN_VALUE>1</MIN_VALUE>
                <MAX_VALUE>5000</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>PACKAGE_HEIGHT</NAME>
                <TYPE>INTEGER</TYPE>
                <MIN_VALUE>1</MIN_VALUE>
                <MAX_VALUE>5000</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>PACKAGE_DEPTH</NAME>
                <TYPE>INTEGER</TYPE>
                <MIN_VALUE>1</MIN_VALUE>
                <MAX_VALUE>5000</MAX_VALUE>
            </ATTRIBUTE>

        </ATTRIBUTES>
    </TABLE>

    <TABLE>
        <NAME>CLIENTS</NAME>
        <ROWS_NUM>100</ROWS_NUM>
        <ATTRIBUTES>
            <ATTRIBUTE>
                <NAME>ID</NAME>
                <TYPE>INTEGER</TYPE>
                <PRIMARY_KEY>true</PRIMARY_KEY>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>FIRST_NAME</NAME>
                <TYPE>VARCHAR</TYPE>
                <MIN_VALUE>2</MIN_VALUE>
                <MAX_VALUE>15</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>LAST_NAME</NAME>
                <TYPE>VARCHAR</TYPE>
                <MIN_VALUE>2</MIN_VALUE>
                <MAX_VALUE>15</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>BIRTH_DATE</NAME>
                <TYPE>TIMESTAMP</TYPE>
            </ATTRIBUTE>

        </ATTRIBUTES>
    </TABLE>

    <TABLE>
        <NAME>ORDERS</NAME>
        <ROWS_NUM>1000</ROWS_NUM>
        <ATTRIBUTES>
            <ATTRIBUTE>
                <NAME>ID</NAME>
                <TYPE>INTEGER</TYPE>
                <PRIMARY_KEY>true</PRIMARY_KEY>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>PRODUCT_ID</NAME>
                <TYPE>INTEGER</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>CLIENT_ID</NAME>
                <TYPE>INTEGER</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>DATETIME</NAME>
                <TYPE>TIMESTAMP</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>STATE</NAME>
                <TYPE>INTEGER</TYPE>
                <VALUES>
                    <VALUE>0</VALUE>
                    <VALUE>1</VALUE>
                    <VALUE>2</VALUE>
                </VALUES>
            </ATTRIBUTE>
        </ATTRIBUTES>
    </TABLE>
</TABLES>

=== klisiecki/SqlDataGenerator/data/simpleStore.xml
<?xml version="1.0"?>
<TABLES xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="pl.poznan.put.sqldatagenerator schema.xsd"
        xmlns="pl.poznan.put.sqldatagenerator" M="200" T="100">
    <TABLE>
        <NAME>PRODUCTS</NAME>
        <ROWS_NUM>50</ROWS_NUM>
        <ATTRIBUTES>
            <ATTRIBUTE>
                <NAME>ID</NAME>
                <TYPE>INTEGER</TYPE>
                <PRIMARY_KEY>true</PRIMARY_KEY>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>PRICE</NAME>
                <TYPE>FLOAT</TYPE>
                <MIN_VALUE>1</MIN_VALUE>
                <MAX_VALUE>10000</MAX_VALUE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>CATEGORY</NAME>
                <TYPE>INTEGER</TYPE>
                <MIN_VALUE>1</MIN_VALUE>
                <MAX_VALUE>5</MAX_VALUE>
            </ATTRIBUTE>

        </ATTRIBUTES>
    </TABLE>

    <TABLE>
        <NAME>CLIENTS</NAME>
        <ROWS_NUM>100</ROWS_NUM>
        <ATTRIBUTES>
            <ATTRIBUTE>
                <NAME>ID</NAME>
                <TYPE>INTEGER</TYPE>
                <PRIMARY_KEY>true</PRIMARY_KEY>
            </ATTRIBUTE>
            <ATTRIBUTE>
                <NAME>AGE</NAME>
                <TYPE>INTEGER</TYPE>
                <MIN_VALUE>10</MIN_VALUE>
                <MAX_VALUE>124</MAX_VALUE>
            </ATTRIBUTE>

        </ATTRIBUTES>
    </TABLE>

    <TABLE>
        <NAME>ORDERS</NAME>
        <ROWS_NUM>1000</ROWS_NUM>
        <ATTRIBUTES>
            <ATTRIBUTE>
                <NAME>ID</NAME>
                <TYPE>INTEGER</TYPE>
                <PRIMARY_KEY>true</PRIMARY_KEY>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>PRODUCT_ID</NAME>
                <TYPE>INTEGER</TYPE>
            </ATTRIBUTE>

            <ATTRIBUTE>
                <NAME>CLIENT_ID</NAME>
                <TYPE>INTEGER</TYPE>
            </ATTRIBUTE>
        </ATTRIBUTES>
    </TABLE>
</TABLES>
